
export interface ClassDetailsForReprint{
    id:number;
    className:string;
    classLogo: string;
    fontName: string;
    fontSize: string;
    fontStyle:string;
    addressLineOne: string;
    addressLineTwo: string;
    fontNameAddress:string;
    fontSizeAddress: string;
    fontStyleAddress: string;
    alignment:string;
    dtDate: string;
    performence: string;
    paperFontSize:string;
    paperFontStyle: string;
    paperFontName: string;
    printLogo:boolean ;
    pdfFormat: boolean;
    docFormat: boolean;
    dblColAuto:boolean;
    dciOneOne: boolean;
    dciFourOne:boolean;
    dclTwoOne: boolean;
    singleAutos: boolean;
    optsNoneOne: boolean;
    optsnTwoOne: boolean;
    optSnFourOne: false
    chkPrintdate: boolean;
    chkPrintClass: boolean;
    chkPrintExamYear: boolean;
    chkAddSpace: boolean;
    chkSemiTransparent: boolean;
    leftAllAlignmentLogo: boolean;
    rightAlignment: boolean;
    watermark: string;
    testHeading:string;
    profileName: string;
    fontNameTestHeading:string;
    fontSizeTestHeading: string;
    fontStyleTestHeading: string;
    fontNameProf: string;
    fontSizeProf: string;
    fontStyleProf:string;
    printProfileName: boolean;
    printTestHeading: boolean;
    optMatDispSelection: boolean;
    printOptionAs: boolean;
    printQuestions: boolean;
    openFileApplication: boolean;
    uniqueClassName: string;
    testPurchased: number;
    narration: string;
    testPurchaseDate: string;
    timeRestriction: boolean;
    mobileTestPurchased: number;
    classAppName: string;
    classAppLogo: string;
    studentCount: number;
    authenticationServer: boolean;
    printUpload: boolean;
    printReview: boolean;
    dateTimeStamp: string;
    matrixPattern: boolean;
    classLogoBinary: string;
}